### PR TITLE
Expose tool pose from RT connection in ROS

### PR DESCRIPTION
**Pull request by sepjansen**
Solution for issue: https://github.com/ThomasTimm/ur_modern_driver/issues/16

Features:
* Broadcast TF between base and tool as reported by UR controller. This is more accurate than the default pose from URDF model. Default base frame is 'base', tool frame is 'tool0_controller', both can be set using parameters
* Publish the tool velocity as TwistStamped with base frame as reference frame on topic 'tool_velocity'

Notes:
* This was tested in simulation and on real UR5 with version 3.0 and 3.1
* To use 'tool0_controller' as link in URDF, a link with that name should be connected to 'base' by a floating joint and the robot_state_publisher should have this fix: https://github.com/ros/robot_state_publisher/pull/32. This was tested and worked correctly.

### CODE REVIEW

**Comment by ThomasTimm** [comment]
Very nice work Simon!

Regarding your last note, am I understanding it correctly that this works with no problems with pre-indigo (the RSP fix is merged into indigo-devel), but the URDF with tool0_controller as a floating joint won't work, right?

**Comment by sepjansen** [comment]
The TF between base and tool frame is broadcasted correctly regardless of the fix in indigo-devel branch of robot_state_publisher, yes. You can view both <b>tool_0</b> and <b>tool0_controller</b> links in RVIZ for your own robot and check the differences between the link poses using tf tooling. You should see a small difference (only on real robots, simulation should match perfectly).

However, to attach links in your URDF to <b>tool0_controller</b> (like gripper links), you need to have a link <b>tool0_controller</b> in your URDF. You basically need a 'dynamic' URDF link, where the actual transform is broadcast by the driver and not by the robot_state_publisher. You can do this by specifying a floating joint, which will only be correctly detected by robot_state_publisher since https://github.com/ros/robot_state_publisher/pull/32.

You can of course always broadcast your own tf between <b>tool0_controller</b> using e.g. static transform broadcaster.

Btw: Do we know if that fix https://github.com/ros/robot_state_publisher/pull/32 is already officially released? I tested by building robot_state_publisher from indigo-devel branch from source.

**Comment by ThomasTimm** [comment]
Great, thanks for clearing that out.

From http://docs.ros.org/indigo/changelogs/robot_state_publisher/changelog.html it looks like it is already in the official release, and thus a `sudo apt-get install ros-indigo-robot-state-publisher` should be sufficient.

**Comment by sepjansen** [comment]
Hmmm... <code>sudo apt-get install ros-indigo-robot-state-publisher</code> does not give me the new functionality, but that's probably another issue.

**Pull request merged**
