### PR TITLE
Initial steps towards converting to standalone (non-ros) driver support.

### PR DESCRIPTION
**Pull request by ahundt**
I've started adapting the code so it can compile and be used without ros. If these first changes work ok for you can you consider merging them and/or patching them to fix any bugs under ros? I don't have ros.

### CODE REVIEW

**Comment by ThomasTimm** [comment]
Hi Andrew

A few comments: 
Your merge request will break the ros implementation, as you comment out relevant files for ros_control in the hardware_interface.h file.

I don't know OSX, but why do you remove the quickack flag from the socket when compiling under Apple? If OSX don't support quickack, I would not advise using OSX together with UR... Alternatively, you need to force an 'ACK' whenever a package is received, i.e. by writing a newline char to the socket.

endian is only an issue when parsing data from the UR. This is exclusively done in the robot_state.cpp and robot_state_RT.cpp files. Thus you don't need to include the portable_endian.h file in any other files. Also, please keep your includes in the header file.

I would recommend you to read my report on the driver (a link is in the bottom of the readme file), where I have described the API. You will find that it is by design very easy to use my driver without ROS. All the ROS specific code is in the two files ur_ros_wrapper.cpp and hardware_interface.cpp (and its header file). So you just need to use the ur_driver.cpp as a library and call its appropriate methods.

Thus the driver can already be used standalone and any further convertion seems redundant. It could be argued that a standalone implementation should include a main function, but it is highly independent and application specific what that main function should do and how to interface to other middleware/code, so I haven't done so.

**Comment by ahundt** [comment]
First, I'd like to thank you for taking a look, and writing the library in the first place. It looks like a pretty good modular design which is why I started modifying it in the first place. 

Have you tried compiling on a clean OS without ros installed? Unfortunately in practice it is much less easy to avoid ROS than you described. 

- Standalone compilation definitely doesn't work because [ros headers are directly included by other headers](https://github.com/ThomasTimm/ur_modern_driver/blob/6c3cade12fb47f41b816d05377feaea993742a28/include/ur_modern_driver/ur_hardware_interface.h#L67). 
- The CMake script also provides [no possibility of not defining `ROS_BUILD`](https://github.com/ThomasTimm/ur_modern_driver/blob/36e20b8567317f5546c5f8add7977491008e243f/CMakeLists.txt#L3).
- [Catkin is endemic throughout the cmakelists.txt](https://github.com/ThomasTimm/ur_modern_driver/blob/36e20b8567317f5546c5f8add7977491008e243f/CMakeLists.txt#L7)
- The libraries are built such that they [include ros dependent sources](https://github.com/ThomasTimm/ur_modern_driver/blob/36e20b8567317f5546c5f8add7977491008e243f/CMakeLists.txt#L155), I suggest having 2 libraries (aka .so/.a files), one that is the independent "core" and the other which adds ros functionality and dependencies.

It looks like OS X can have an [equivalent to quick ack](https://rolande.wordpress.com/2014/05/17/performance-tuning-the-network-stack-on-mac-os-x-part-2/
) set in the OS config. However, the header definition is linux only and not supported on any other OS.

Thanks again for your time and consideration.

**Comment by ThomasTimm** [comment]
I don't think my supervisor has ROS on his computer (at least not something updated :P ), and he is using my driver in his own code.

  * Please re-read my previous post... the ur_hardware_interface.cpp/.h file is only relevant for ROS. In your case, simply don't include that file. All it does it setup some external hooks for ros_control to populate variables, whose values are then sent to the UrDriver class. 
The UrDriver class doesn't depend on hardware_interface. I guess my poor file name choice is the cause of the confusion; the name is chosen as it is commonly used in ros_control implementations and reflect that it interfaces the hardware to ros_control, not that it is the actual lowest-level hardware interface.
  * I am in no way an expert in CMake or compilers, but not having defined `ROS_BUILD` shouldn't be a problem? (Again, my supervisor is compiling with no issues, using his own Makefile ). 
You should be able to compile by going into the `src` directory and simply type something similar to `gcc -std=c++11 -I../include ur_driver_standalone.cpp ur_driver.cpp ur_realtime_communication.cpp ur_communication.cpp robot_state.cpp robot_state_RT.cpp do_output.cpp -pthread`. Note I haven't tested that command, so it might contain typos, just wrote it out of memory.
  * I only ever intended for the CMakelists.txt to be used in ROS. If using the driver in standalone, I always assumed people would make their own Makefile to include the files they need (main file as well as supporting files for interfacing with the world). 
  * I agree with you on the library point. I initially also intended to make two libraries, but apparently forgot.

you should then set the delayed_ack to 0 if __APPLE__ is defined, otherwise you will get really crappy data flow from the robot.

**Comment by ahundt** [comment]
Ok the ros bit should no longer be broken, and there is now a standalone lib created when ros isn't available

**Comment by ahundt** [comment]
how would you feel about some way to quickly differentiate between code for ros/non ros use cases?

One example would be prefixing ros specific headers with ros_.

**Comment by ahundt** [comment]
I also added an initial implementation of a super simple interface for those who only care minimally about the details.

**Comment by ahundt** [comment]
@ThomasTimm any possibility of merging this?

**Comment by shivesh1210** [comment]
Hi Andrew, 
Maybe I am in a similar position as yours. I want to use this driver standalone and integrate it with our robot operating system called RoCK. If you have already created a standalone version of it, where can I download it? 
Best Regards,
Shivesh

**Comment by ahundt** [comment]
@shivesh1210 Here is the location of my fork https://github.com/ahundt/ur_modern_driver I'm not sure if it is standalone in the way you are looking for or not.

**Comment by shivesh1210** [comment]
Thanks a lot Andrew. I tried using your fork and I get this error: 
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
initializingur_hardware_interface_standalone:Loaded ur_hardware_interface_standalone.Aborted (core dumped)
This is my main.cpp:
#include <iostream>
#include "ur_hardware_interface_standalone.h"

using namespace std;
using namespace ur;
int main(){
cout<<"Hello World"<<endl;	
UrHardwareInterfaceStandalone obj("10.250.3.100");

}
Could you please help me fix the error or send me your main.cpp file so that I can get started?

**Comment by shivesh1210** [comment]
Hey Andrew, I solved the above issue by linking the library with Threads. Now I have another question about your implementation. I am getting this error: ur_driver_bin: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = UrDriver; typename boost::detail::sp_member_access<T>::type = UrDriver*]: Assertion `px != 0' failed.

Maybe it is because the variable robot is never assigned to the internal variable robot_?

**Comment by ahundt** [comment]
@shivesh1210 yeah these changes still need some debugging... sorry about that! thanks for the tip regarding threads. This is a runtime error it looks like, and it means that the shared pointer is null. It seems some step needed to initialize the shared pointer is being skipped. Can you get a stack trace?

**Comment by ThomasTimm** [comment]
The intention of this repo is to have a ROS driver. 
Those looking for a stand-alone driver that can't figure out how to compile it without ROS should have a look at https://github.com/ahundt/ur_modern_driver

**Pull request closed without merging**
